/* A packrat parser generated by PackCC 1.5.1 */

#ifndef PCC_INCLUDED_GRAMMAR_H
#define PCC_INCLUDED_GRAMMAR_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct cactus_context_tag cactus_context_t;

cactus_context_t *cactus_create(void *auxil);
int cactus_parse(cactus_context_t *ctx, int *ret);
void cactus_destroy(cactus_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_GRAMMAR_H */
